/-
 Copyright Cedar Contributors

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-/

import FormatSpec.Syntax
import FormatSpec.Decode
import FormatSpec.Decidable

/-!
# Decimal demo: input the grammar, get the spec

Transcribes `doc/CedarDoc/Decimal.lean` into one `format_spec` block and exercises the
generated spec (`grammar`, `constraints`, `valueExpr`) end-to-end via `decode`,
`computeValue`, and the decidable recognizer `IsWf`.
-/

namespace FormatSpec.DecimalDemo
open FormatSpec

-- ════════════════════════════════════════════════════════════════════════════
--  INPUT — the doc's Decimal grammar + constraint + value, transcribed
-- ════════════════════════════════════════════════════════════════════════════
--   Decimal  ::= Integer '.' Fraction
--   Integer  ::= ['-'] Digit⁺
--   Fraction ::= Digit{1,4}
--   value(Decimal) = int(Integer)·10⁴ + sign·nat(Fraction)·10^(4 − |Fraction|)
--   Constraint: value ∈ [Int64.MIN, Int64.MAX]   (Int64 range; -2^63 .. 2^63-1)
-- `to "…"` writes the generated declarations (drop-in, with imports) to that file,
-- in addition to elaborating them here. Building this demo (re)generates the file.
format_spec Decimal where
  grammar
    Decimal  ::= Integer "." Fraction
    Integer  ::= ["-"] digit+
    Fraction ::= digit{1,4}
  value
    int Integer * 10 ^ 4 + sign Integer * nat Fraction * 10 ^ (4 - len Fraction)
  constraints
    value ∈ [Int64.MIN, Int64.MAX]
  to "FormatSpec/Generated/Decimal.lean"

-- ════════════════════════════════════════════════════════════════════════════
--  OUTPUT — the generated spec, run on sample strings
-- ════════════════════════════════════════════════════════════════════════════

-- The generated declarations — ingredients AND the bundled spec predicates:
#check (Decimal.grammar     : Grammar)
#check (Decimal.constraints : List ConstraintEntry)
#check (Decimal.valueExpr   : ValExpr)
#check (Decimal.isWf                 : String → Prop)
#check (Decimal.satisfiesConstraints : String → Prop)
#check (Decimal.isAccepted           : String → Prop)

-- `decode` extracts the captures:  "1.5" ↦ Integer="1", Fraction="5"
#eval decode Decimal.grammar "1.5"       -- some [("Integer","1"), ("Fraction","5")]
#eval decode Decimal.grammar "-12.34"    -- some [("Integer","-12"), ("Fraction","34")]
#eval decode Decimal.grammar "1.x"       -- none (fraction not digits)
#eval decode Decimal.grammar "1"         -- none (no '.')

-- `computeValue` = eval the value formula on the decoded captures (fixed-point ×10⁴):
#eval computeValue Decimal.grammar Decimal.valueExpr "1.2345"   -- some 12345
#eval computeValue Decimal.grammar Decimal.valueExpr "1.5"      -- some 15000
#eval computeValue Decimal.grammar Decimal.valueExpr "-1.5"     -- some (-15000)
#eval computeValue Decimal.grammar Decimal.valueExpr "1.x"      -- none

-- Executable validator via the total boolean recognizer `recognize` (fully proved, no
-- `sorry`). `recognize` decides `IsWf` (`recognize_iff`), which also gives
-- `DecidablePred (IsWf g)`; but `decide (IsWf …)` currently routes through the one
-- remaining `sorry` (`recognizeProd_iff`), so we run `recognize` directly here.
#eval recognize Decimal.grammar "1.5"       -- true
#eval recognize Decimal.grammar "1.x"       -- false
#eval recognize Decimal.grammar "12.3456"   -- true

-- `decode` (the total capture extractor) agrees on validity:
#eval (decode Decimal.grammar "1.5").isSome  -- true

-- ── The BUNDLED spec predicates (generated by the command) ──
-- `isAccepted` = well-formed ∧ all constraints hold.
#eval decide (Decimal.isWf "1.5")        -- true
#eval decide (Decimal.isAccepted "1.5")  -- true  (well-formed and in Int64 range)
#eval decide (Decimal.isAccepted "1.x")  -- false (not well-formed)

-- ── Per-production well-formedness (generated: one `IsWf` Prop per production) ──
-- Inlined structural predicates (∃ named captures, s = … ∧ …), reading like the hand
-- specs (`IsWfDatetime`, `IsWfV4`). Naming: capital-`I` `Decimal.IsWf.*` = the SURFACE
-- Prop you read/prove; lowercase `Decimal.isWf` = the behind-the-scenes decidable checker.
#check (Decimal.IsWf.Integer  : String → Prop)
#check (Decimal.IsWf.Fraction : String → Prop)
-- the top-level `IsWf` equals the start production's `IsWfProd`, pointwise (proved once
-- generically in `Denote` as `isWf_eq_isWfProd_start`):
example (s : String) : IsWf Decimal.grammar s = IsWfProd Decimal.grammar "Decimal" s :=
  isWf_eq_isWfProd_start Decimal.grammar s

/-!
NOTE on proofs vs. `#eval`: the recognizers use `mutual`/well-founded recursion, which
compiles to `WellFounded.fix` — opaque to the kernel, so `by decide` cannot reduce it,
and we deliberately avoid `native_decide` (it would add the `ofReduceBool` axiom to the
trust base). So this demo uses `#eval` (compiled evaluation, adds NO axiom to any
theorem) to *illustrate* behavior. Actual correctness comes from hand-proved contract
theorems, not from `decide`-ing specific inputs.
-/

-- ════════════════════════════════════════════════════════════════════════════
--  CONTRACT THEOREMS — emitted as `sorry`d obligations against an external parser
-- ════════════════════════════════════════════════════════════════════════════

-- A stand-in "external" parser + projection, to demonstrate the `parser` clause. In real
-- use these name the hand-written Cedar parser (e.g. `Cedar.Spec.Ext.Decimal.parse`) and
-- its `Int` projection (`fun d => d.toInt`).
structure DemoDec where val : Int
def demoParse (s : String) : Option DemoDec := (computeValue Decimal.grammar Decimal.valueExpr s).map DemoDec.mk
def demoProj (d : DemoDec) : Int := d.val

-- The `parser` clause makes the command emit the contract obligations as sorried thms.
format_spec DecimalWithParser where
  grammar
    Decimal  ::= Integer "." Fraction
    Integer  ::= ["-"] digit+
    Fraction ::= digit{1,4}
  value
    int Integer * 10 ^ 4 + sign Integer * nat Fraction * 10 ^ (4 - len Fraction)
  constraints
    value ∈ [Int64.MIN, Int64.MAX]
  parser demoParse projection demoProj

-- The emitted obligations (all `sorry`d — the proof-facing deliverable):
#check (DecimalWithParser.sound    : SoundStmt _ _ _ demoParse demoProj)
#check (DecimalWithParser.complete : CompleteStmt _ _ _ demoParse demoProj)
#check (DecimalWithParser.reject   : RejectStmt _ _ demoParse)

end FormatSpec.DecimalDemo
