-- Generated by FormatSpec from `format_spec Graph`. Do not edit by hand.

import FormatSpec.Denote
import FormatSpec.Value
import FormatSpec.Constraint
import FormatSpec.Assemble
import FormatSpec.Reconcile
import FormatSpec.Examples.Graph.grammar

open FormatSpec
open FormatSpec.Examples.Graph

set_option linter.unusedSimpArgs false
set_option linter.unusedVariables false

-- ═══════════════════════════════ spec ═══════════════════════════════
-- The reader-facing specification: the grammar, the readable per-production
-- well-formedness predicates `IsWf.*`, the `value` function, the `Constraints`,
-- and the acceptance predicates `SatisfiesConstraints` / `IsValid` (a string is
-- VALID iff it satisfies the grammar and constraints — Cedar's wording).

def Graph.grammar : Grammar :=
  Grammar.mk "G"
    [Production.mk "G"
        [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
            SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]],
      Production.mk "E01" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]],
      Production.mk "E02" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]],
      Production.mk "E12" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]]]

def Graph.IsWf.E01 (s : String) : Prop :=
  s = "0" ∨ s = "1"

def Graph.IsWf.E02 (s : String) : Prop :=
  s = "0" ∨ s = "1"

def Graph.IsWf.E12 (s : String) : Prop :=
  s = "0" ∨ s = "1"

def Graph.IsWf.G (s : String) : Prop :=
  ∃ e01 e02 e12, ((s = e01 ++ " " ++ e02 ++ " " ++ e12 ∧ Graph.IsWf.E01 e01) ∧ Graph.IsWf.E02 e02) ∧ Graph.IsWf.E12 e12

def Graph.value (e01 : String) (e02 : String) (e12 : String) :=
  toGraph3 e01 e02 e12

abbrev Graph.SatisfiesConstraints (s : String) : Prop :=
  True

abbrev Graph.IsValid (s : String) : Prop :=
  Graph.IsWf.G s ∧ Graph.SatisfiesConstraints s

-- ══════════════════════════════ engine ══════════════════════════════
-- The analyzable/executable machinery behind the spec: the deep-embedded
-- value/constraint ASTs and the decode-backed interpreter bundle (`isWf`,
-- `isValid`, `computeValue`).

def Graph.valueFn := fun env : Env =>
  toGraph3 (((env : Env) "E01").getD "") (((env : Env) "E02").getD "") (((env : Env) "E12").getD "")

def Graph.constraints : List ConstraintEntry :=
  []

abbrev Graph.isWf (s : String) : Prop :=
  FormatSpec.isWf Graph.grammar Graph.constraints s

abbrev Graph.satisfiesConstraints (s : String) : Prop :=
  FormatSpec.satisfiesConstraints Graph.grammar Graph.constraints s

abbrev Graph.isValid (s : String) : Prop :=
  Graph.isWf s ∧ Graph.satisfiesConstraints s

def Graph.computeValue (s : String) :=
  FormatSpec.computeValueF Graph.grammar Graph.valueFn s

-- ════════════════════════════ soundness ════════════════════════════
-- The guarantees tying the two together: the surface⟺engine equivalence
-- `IsWf_equiv` (+ its `Internal.matchesRef.*` lemmas) and the derived
-- `DecidablePred IsWf.*` instance (an executable validator, via the interpreter).

theorem Graph.Internal.matchesRef.E01 (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "E01") s ↔ Graph.IsWf.E01 s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "E01" =
        some (Production.mk "E01" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]])
      from rfl]
  dsimp only
  unfold matchesProd Graph.IsWf.E01
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Graph.Internal.matchesRef.E02 (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "E02") s ↔ Graph.IsWf.E02 s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "E02" =
        some (Production.mk "E02" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]])
      from rfl]
  dsimp only
  unfold matchesProd Graph.IsWf.E02
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Graph.Internal.matchesRef.E12 (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 1) (Sym.ref "E12") s ↔ Graph.IsWf.E12 s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "E12" =
        some (Production.mk "E12" [[SymItem.mk (Sym.lit "0") false], [SymItem.mk (Sym.lit "1") false]])
      from rfl]
  dsimp only
  unfold matchesProd Graph.IsWf.E12
  simp (config := { maxSteps := 1000000 }) only [List.mem_cons, List.mem_singleton, List.not_mem_nil,
    FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_or_imp, exists_eq_left, exists_eq_left, if_true,
    if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym]
  repeat'
    first
    | apply or_congr
    | ( simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left,
          ← and_assoc, exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
        try grind [String.append_assoc, String.append_empty])

theorem Graph.Internal.matchesRef.G (fuel : Nat) (s : String) :
    matchesSym Graph.grammar (fuel + 2) (Sym.ref "G") s ↔ Graph.IsWf.G s :=
  by
  rw [matchesSym,
    show
      (Graph.grammar).prod? "G" =
        some
          (Production.mk "G"
            [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
                SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]])
      from rfl]
  dsimp only
  rw [matchesProd_single]
  unfold Graph.IsWf.G
  simp (config := { maxSteps := 1000000 }) only [FormatSpec.matchesSeq.eq_1, FormatSpec.matchesSeq.eq_2, exists_eq_left,
    if_true, if_false, Bool.false_eq_true, false_and, or_false, or_assoc, FormatSpec.matchesSym,
    Graph.Internal.matchesRef.E01, Graph.Internal.matchesRef.E02, Graph.Internal.matchesRef.E12]
  simp (config := { maxSteps := 1000000 }) only [String.append_assoc, String.append_empty, exists_and_left, ← and_assoc,
    exists_eq_left, exists_eq_left', exists_eq_right, and_true, Option.some.injEq, forall_eq']
  try grind [String.append_assoc, String.append_empty]

theorem Graph.IsWf_equiv (s : String) : IsWf Graph.grammar s ↔ Graph.IsWf.G s :=
  by
  rw [isWf_eq_isWfProd_start, IsWfProd,
    show
      (Graph.grammar).prod? (Graph.grammar).start =
        some
          (Production.mk "G"
            [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
                SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]])
      from rfl]
  have hstart :
    ∀ n,
      matchesProd Graph.grammar n
          (Production.mk "G"
            [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
                SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]])
          s =
        matchesSym Graph.grammar (n + 1) (Sym.ref "G") s :=
    by
    intro n
    rw [matchesSym,
      show
        (Graph.grammar).prod? "G" =
          some
            (Production.mk "G"
              [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
                  SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]])
        from rfl]
  show
    matchesProd Graph.grammar (Graph.grammar).prods.length
        (Production.mk "G"
          [[SymItem.mk (Sym.ref "E01") false, SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E02") false,
              SymItem.mk (Sym.lit " ") false, SymItem.mk (Sym.ref "E12") false]])
        s ↔
      _
  rw [hstart]
  exact Graph.Internal.matchesRef.G _ s

instance Graph.instDecidableIsWf : DecidablePred Graph.IsWf.G := fun s =>
  @decidable_of_iff _ _ (Graph.IsWf_equiv s) (FormatSpec.decIsWf Graph.grammar (by decide) s)

instance Graph.instDecidableIsValid : DecidablePred Graph.IsValid := fun s => inferInstanceAs (Decidable (_ ∧ _))

theorem Graph.IsValid_equiv (s : String) : Graph.IsValid s ↔ Graph.isValid s :=
  by
  unfold Graph.IsValid Graph.isValid Graph.isWf Graph.satisfiesConstraints
  unfold FormatSpec.isWf FormatSpec.satisfiesConstraints
  rw [← Graph.IsWf_equiv, ← decodeSome_iff_IsWf Graph.grammar (by decide)]
  unfold Graph.SatisfiesConstraints Graph.constraints
  simp only [FormatSpec.component, List.forall_mem_cons, List.forall_mem_singleton, List.not_mem_nil, forall_const,
    if_true, if_false, ConstraintEntry.wfPart, ConstraintEntry.valPart, Constraint.wfPart, Constraint.valPart,
    Constraint.isValueDependent, Constraint.eval, ValExpr.eval, presentCount, natOf_getD, intOf_getD, lenOf_getD,
    signOf_getD, and_true, true_and, false_implies, implies_true, Bool.false_eq_true]
  try grind
